### ISSUE TITLE
pipenv support

### ISSUE THREAD

**Issue by stefanhoelzl** [theacodes/nox#159]
**How would this feature be useful?**
nox could be used easily with [pipenv](https://pipenv.readthedocs.io/en/latest/) based projects.
Havent used nox yet, but when having this feature, I would use it for my projects.

**Describe the solution you'd like**
The following code would use the Pipfile and pipenv in the project directory to setup the virtualenv.
```python
@nox.session(python=['2.7', '3.6'], pipenv=True)
def tests(session):
    …
```

Alternative, when needing`dev-packages` specified the Pipfile
```python
@nox.session(python=['2.7', '3.6'], pipenv="dev")
def tests(session):
    …
```

**Describe alternatives you've considered**
Not sure if there is another way to use nox with pipenv based projects.

I would help out implementing/testing this feature!

**Comment by stsewd** [comment]
Tox already manage the virtualenvs creation, so I guess you can only call `session.run('pipenv', 'install')`, pipenv should detect that it's inside a virtualenv and not create a new one.

**Comment by stefanhoelzl** [comment]
Thanks! I will give it a try.

**Comment by theacodes** [comment]
Hey @stefanhoelzl, were you able to solve your use case to a good extent with the existing featureset? Do you think we should add any more features for this? Should we add a section to the docs explicitly on using pipenv?

**Comment by stefanhoelzl** [comment]
Hi,

did only a short test and it worked fine for me!
But since I got another dependency which doesn't work well with `pipenv` I moved back to the good old requirements.txt and couldn't test `nox` and `pipenv` in depth.

Maybe you could add, what @stsewd wrote, to the docs. That `pipenv` detects the created `virtualenv`.
It would clarify that `nox` and `pipenv` can be used together.

**Comment by theacodes** [comment]
Cool call. Thanks for following up!

**Comment by theacodes** [comment]
The groundwork for this was set in #217 so that should be a good reference for anyone who wants to try implementing this.

**Comment by skshetry** [comment]
I am interested to work on this. I have a few questions regarding the implementation:

1. As pipenv already detects the virtualenv, would it be just good to use virtualenv created by nox?
2. I don't think `nox` activates the virtualenv, so, `pipenv` won't be able to detect. Maybe provide `VIRTUAL_ENV` env variable?
3. Should it allow installing other dependencies rather than from Pipfile? Also, should lock file update? I guess it'd be better to only allow installing from lockfile similar to what `pipenv sync`.
4. Something like following would work?
    ```python
    session.pipenv_install(dev=True)
    ```
    But, if later `poetry` or similar tools are added, it'll need to add another method: `poetry_install`.

**Comment by cjolowicz** [comment]
> 2\. I don't think `nox` activates the virtualenv, so, `pipenv` won't be able to detect. Maybe provide `VIRTUAL_ENV` env variable?

This issue also affects projects managed by [Poetry](https://poetry.eustace.io/). 

When invoked from a nox session, Poetry does not use the virtualenv created by nox. This appears due to the fact that `session.run` does not actually activate the virtualenv. Instead, it simply locates the command in the virtualenv's bin directory.

Passing `VIRTUAL_ENV` explicity fixes the problem. See below for an example:

```python
@nox.session(python="3.7")
def tests(session):
    """Run the test suite."""
    tests = session.posargs or ["tests/"]
    env = {"VIRTUAL_ENV": session.virtualenv.location}
    session.run("poetry", "install", external=True, env=env)
    session.run("poetry", "run", "pytest", *tests, external=True, env=env)
```
