### ISSUE TITLE
Include Conda-install package functionality

### ISSUE THREAD

**Issue by Pragnya02** [theacodes/nox#183]
**How would this feature be useful?**
Reading the documentation , nox provides automated pip-install packages feature ( that can be defined in the configuration file).
 It would be useful to support conda-install as well , to be able to include installing miniconda/anaconda package install .

I would like to work on this as my first contribution , if anyone could help me get started, would be really helpful!

**Comment by tswast** [comment]
I would find this useful for testing pandas-gbq as well.

Would you create conda envs instead of virtual envs? I recall that using a virtual env inside conda is not supported.

**Comment by Pragnya02** [comment]
Not sure if I understood your question right , but virtual env can be created using conda, and that should support conda install + pip install within that .

**Comment by tswast** [comment]
`nox` is intended to support multiple versions of Python, but within a conda env, you can only have a single Python executable available. This will cause problems when `nox` creates the virtualenv because it will likely find either no Python for the desired version or a Python that is not managed by conda .(See: https://github.com/theacodes/nox/blob/cede4472651c4902ea66d630bd52345885cd685c/nox/virtualenv.py#L205 for the command that creates the virtualenv)

**Comment by tswast** [comment]
I'm pretty sure that what is needed to support this use case is to be able to create conda envs instead of virtualenvs, that way conda can be used to pick the python interpreter rather than virtualenv. Alternatively, maybe some logic to detect what Python interpreters are available from conda and switch to the right one before creating the virtualenv.

**Comment by theacodes** [comment]
I would love to see this feature, but I have limited knowledge of Conda. Someone else will need to sketch out what this should look like, but once y'all have an idea I'm happy to review the PR. :)

**Comment by Pragnya02** [comment]
Thank you @theacodes and @tswast .
Could I get a heads up on what module/functionality should I look into to get started with ?

**Comment by theacodes** [comment]
You'll probably just have a to make a subclass/sisterclass of our
`virtualenv` module. We already have a similar thing with ProcessEnv vs
VirtualEnv. I'd imagine we'd end up with ProcessEnv, VirtualEnv, and
CondaEnv.

**Comment by pylang** [comment]
One project that has made some traction with tox + conda is the  `tox-conda` plugin https://github.com/tox-dev/tox-conda.  This may be the sketch you're seeking @theacodes.

A shining feature when using conda over a pip backend is that downloading the scipy stack takes seconds to install instead of minutes.  Example: try installing `panda`, `numpy`, `scipy`, `matplotlib`,  and `notebook` using native tox (via pip).  Then try the same using `tox-conda` by installing the plugin and modifying the `.ini` file.  The benefits become self-evident.

**Comment by theacodes** [comment]
Thanks for sharing the tox-conda stuff. I'm sure that'll be helpful.

I think we're all aware of the benefits of conda for scientific packages, which is why we're open to this. :)

**Comment by tswast** [comment]
I created a draft PR to add conda support. https://github.com/theacodes/nox/pull/215

I used the suggested `venv_backend` option from #199 and added a `session.conda_install()` function so that `pip` and `conda` can be used in the same session when needed.
