### ISSUE TITLE
Add an option to not changed directory to the one the noxfile is in.

### ISSUE THREAD

**Issue by Peilonrayz** [theacodes/nox#197]
**How would this feature be useful?**

Currently I'm writing a wrapper to Nox that doesn't publicly expose the `noxfile.py`. Nox then changes directory to my package with no clean way to not do this or get back.

**Describe the solution you'd like**

 - Add a `--cwd` argument that allows the user to specify the directory they want to work in. Or,
 - Add a `--no-change-cwd` flag that disables changing the CWD.

**Describe alternatives you've considered**

 - Locally I've removed [tasks.py#55](https://github.com/theacodes/nox/blob/1709f163505d7a1af54b1078f8cc5527bf05eb74/nox/tasks.py#L55) which has fixed this.*

    Given the comment above this line I don't think this is a valid solution.

 - Pre-invocation of Nox I could add a file to where I know Nox will change directory. This file will contain the directory I actually want to be in. I could then change directory in each session from this file.

    This is really a hack, not a solution.

\* It should be noted when removing tasks.py#55, each session is in the unwanted directory but not the global scope. This can be solved by adding the CWD to the global scope and changing in each session. I'm unsure what's causing this however.

**Comment by theacodes** [comment]
Hmm. I'm unsure on this one. I like *well defined behavior* and I like noxfiles having the guarantee that their cwd is the same directory that they're in.

/cc @lukesneeringer @crwilcox @dhermes @stsewd thoughts?

**Comment by dhermes** [comment]
Well I don't see

```python
os.chdir(os.path.realpath(os.path.dirname(global_config.noxfile)))
```

as being strictly necessary to satisfy the stated reason

> This will ensure that the Noxfile's path is on `sys.path`

This could also be accomplished by modifying / verifying `sys.path`

**Comment by stsewd** [comment]
> I like noxfiles having the guarantee that their cwd is the same directory that they're in.

I'm +1 on this, If you wan to change the cwd, you can just use `session.cd` https://nox.thea.codes/en/latest/config.html#nox.sessions.Session.cd Otherwise, it wouldn't be deterministic and annoaying to change directories instead of doing `nox -f foo/bar/noxfile.py`.

I don't fully understand the use case, but you could pass the cwd form the wrapper as a posarg maybe?

Also, maybe nox could provide a way to get the _original_ cwd.

**Comment by Peilonrayz** [comment]
> This could also be accomplished by modifying / verifying `sys.path` - dhermes 

I may be wrong, but it doesn't seem like changing `sys.path` is a requirement. Removing tasks.py#55 and using `nox -f not_in_path/noxfile.py` works just fine.

> If you wan to change the cwd, you can just use session.cd - stsewd 

That doesn't solve the problem unless tasks.py#55 is removed, as there's no way to get the old CWD.

> Otherwise, it wouldn't be deterministic and annoaying to change directories instead of doing nox -f foo/bar/noxfile.py.

I don't see how `--cwd` wouldn't be deterministic.

It can also just default to the value tasks.py#55 changes to. Which would make it exactly the same as `nox -f foo/bar/noxfile.py` with the option for me to do `nox -f foo/bar/noxfile.py --cwd .`.

> I don't fully understand the use case, but you could pass the cwd form the wrapper as a posarg maybe? - stsewd

No as I need access to a user defined config file to make the functions wrapped in `nox.session`. Take the following MVCE:

```
import json

import nox


def build_task(task):
    def function(session) -> None:
        session.install(*task['deps'])
        session.run(*task['command'])

    function.__name__ = task['name']
    return nox.session(function)


with open('./user_config.json') as config_obj:
    for task in json.load(config_obj):
        build_task(task)
```

> maybe nox could provide a way to get the original cwd.

I'd be happy with that, but it'd have to be available from `nox`, not `session`. As shown above.

**Comment by crwilcox** [comment]
The noxfile today assumes all paths are relative to the file itself. I don't quite follow what use case this resolves. It seems like maybe you have a repository that isn't using nox but you would like to but not check in the noxfile, so you keep it out of that directory tree? In this case it seems straightforward to cd in the nox session since the path won't be variable.

Regarding cwd being deterministic: The issue is there are multiple ways a noxfile author could implicitly require the working directory to match. While in your case you have prepared for that, this argument could be used by any passerby on any noxfile. So creating a situation where an arg could have unintended side effects to an execution could be problematic.

**Comment by Peilonrayz** [comment]
@crwilcox As I said before I can't cd in the session, because, as the code I provided above shows, it requires to be in the correct directory to create the session objects. And nox is preventing that from happening.

---

I'm just going to close this, as I don't see this feature request having a future even if I were to submit a PR.
