### ISSUE TITLE
pip not found while debugging in pycharm

### ISSUE THREAD

**Issue by omry** [theacodes/nox#238]
That's a weird one.
I am trying to debug a unit test problem that shows up only inside nox under Pycharm.
somehow, when I run nox normally under it (as a module), it runs correctly but when I run it in debug mode I get errors about pip not being found.
This only happens when I run it in debug under pycharm, and I wouldn't be surprised if it's somehow responsible.

Output:
```
/miniconda3/envs/hydra36/bin/python /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --module --multiproc --qt-support=auto --client 127.0.0.1 --port 56067 --file nox -s "test_plugin-3.6(example_plugin, pip install -e .)" -- -k test_custom_task_name[hydra_config1-extra_flags1-hydra_plugins.fairtask-None-overrides0-no_config.py-no_config]
pydev debugger: process 55292 is connecting

Connected to pydev debugger (build 191.7479.30)
Running session test_plugin-3.6(example_plugin, pip install -e .)
Creating virtualenv using python3.6 in .nox/test_plugin-3-6-example_plugin-pip-install-e
pip install --upgrade setuptools pip
Error: pip is not installed into the virtualenv, it is located at /miniconda3/envs/hydra36/bin/pip. Pass external=True into run() to explicitly allow this.
Session test_plugin-3.6(example_plugin, pip install -e .) failed.

Process finished with exit code 1
```
I tried stepping into nox a bit but was not able to quickly figure out what's happening.

**Comment by theacodes** [comment]
Seems it's happening in a conda env? I personally don't know much about conda but maybe @tswast has some ideas.

**Comment by omry** [comment]
Yup, in a Conda environment.
I think Pycharm is also a critical component of this mess though.

**Comment by omry** [comment]
Also reproduce with the system interpreter on my Mac.

```
/usr/local/bin/python3 /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --module --multiproc --qt-support=auto --client 127.0.0.1 --port 59586 --file nox -s "test_plugin-3.6(example_plugin, pip install -e .)" -- -k test_custom_task_name[hydra_config1-extra_flags1-hydra_plugins.fairtask-None-overrides0-no_config.py-no_config]
pydev debugger: process 65870 is connecting

Connected to pydev debugger (build 191.7479.30)
Running session test_plugin-3.6(example_plugin, pip install -e .)
Creating virtualenv using python3.6 in .nox/test_plugin-3-6-example_plugin-pip-install-e
pip install --upgrade setuptools pip
Error: pip is not installed into the virtualenv, it is located at /miniconda3/bin/pip. Pass external=True into run() to explicitly allow this.
Session test_plugin-3.6(example_plugin, pip install -e .) failed.

Process finished with exit code 1

```

**Comment by tswast** [comment]
`/miniconda3/bin/pip` appears to belong to the base environment. `/miniconda3/envs/hydra36/bin/pip` appears to belong to the `hydra36` base environment. I don't know why these binaries would be chosen instead of the pip package in the created virtualenv, though.

Perhaps https://github.com/JetBrains/intellij-community/blob/ea8b4605b3505a7c6abbe532e627076b388ccd31/python/helpers/pydev/pydevd.py#L1815 is a clue? Nox is definitely forking processes, so maybe this reset logic is also wiping out the environment variables from the virtualenv?

**Comment by busunkim96** [comment]
I started seeing a similar error (wrong pip detected) recently. In my case it seems to have been the combination of using 3.6.1 with virtualenv>=20.0.0. The root cause is probably different, but I thought it would be worth sharing how I debugged it.

I switched `log=True` on this line and found out that the virtualenv was created in the wrong directory (`.nox` instead of `.nox/blacken` for the session named `blacken`). 

https://github.com/theacodes/nox/blob/06180bdff3bbbc2e7ff9d728bb48106330814d6a/nox/virtualenv.py#L353

If you haven't already, it might be worth inspecting the virtualenv directory created by nox (`.nox/test_plugin-3-6-example_plugin-pip-install-e`) to make sure it exists and has the expected structure.

```sh
# Assumes Python 3.6.1
python3 -m pip install virtualenv==20.0.4

# Try to make virtualenv in a nested directory 'b/c/d' that doesn't exist
# virtualenv is created at top-level 'b' instead
busunkim@busunkim:~$ python3 -m virtualenv b/c/d
created virtual environment in 202ms CPython3Posix(dest=/usr/local/google/home/busunkim/b, clear=False, global=False) with seeder FromAppData pip=latest setuptools=latest wheel=latest app_data_dir=/usr/local/google/home/busunkim/.local/share/virtualenv/seed-v1 via=copy
```

**Comment by theacodes** [comment]
This issue has gone stale and I don't think there's anything actionable for us to do here. I'm going to close it, but if there's still something worth looking into feel free to comment and I'll re-open.
