### ISSUE TITLE
Allow whitelisting of external commands

### ISSUE THREAD

**Issue by skshetry** [theacodes/nox#246]
**How would this feature be useful?**

Running external commands such as `poetry`/`pipenv` need to be explicitly mentioned in `session.run`. It'd be great if some commands are allowed to run without specifying as such.

**Describe the solution you'd like**

Something like the following?:
```python
nox.options.whitelist_externals = ["./test_runner.sh"]
```
[`tox` has it implemented](https://tox.readthedocs.io/en/latest/example/basic.html#whitelisting-non-virtualenv-commands).

**Describe alternatives you've considered**

The alternative is just using `session.run("./test_runner.sh", external=True)`.

**Comment by theacodes** [comment]
I'm not super wild on having more than one way to do something, and
global/command line options are generally reserved for invocation or system
specific configuration. Since externals need to work more or less across
invocations and systems I don't think it's the right place.

However, I am interested to understand why the existing method of using
external=True doesn't work for your use case.

**Comment by theacodes** [comment]
This issue has gone stale. I'm going to close it, but if there's still interest in this I'm happy to re-open.
