### ISSUE TITLE
Command line: handle additional arguments as posargs

### ISSUE THREAD

**Issue by pfmoore** [theacodes/nox#261]
**How would this feature be useful?**
At the moment, invoking `nox` with trailing arguments gives an error:

```
>nox serve
usage: nox [-h] [--version] [-l] [-s [SESSIONS [SESSIONS ...]]] [-k KEYWORDS]
           [-v] [-r] [--no-reuse-existing-virtualenvs] [-f NOXFILE]
           [--envdir ENVDIR] [-x] [--no-stop-on-first-error]
           [--error-on-missing-interpreters]
           [--no-error-on-missing-interpreters] [--error-on-external-run]
           [--no-error-on-external-run] [--install-only] [--report REPORT]
           [--non-interactive] [--nocolor] [--forcecolor]
           ...
nox: error: Unknown argument(s) 'serve'.
```

This is not very useful. Allowing additional arguments to be handled as a `posargs` array (without needing `--`) would make for more natural command line usage in certain cases:

```python
import nox

@nox.session
def admin(session):
    session.install("nikola")
    session.cd("website")
    if session.posargs[0] == "build":
        session.run("nikola", "build")
    elif session.posargs[0] == "serve":
        session.run("nikola", "serve")
    else:
        print("Unknown admin command:", session.posargs[0])
```

With the above noxfile, `nox serve` reads much better than `nox -- serve`.

**Describe the solution you'd like**
Allow posargs to be recognised without needing `--`. As far as I can see there is no conflict, as nox currently does not take non-optional command line arguments at all.

I don't know how hard this would be to implement in practice - my understanding was that `argparse` (which I think `nox` uses) doesn't require the `--`, which suggests that special effort might have been made to require it - in which case, implementation may be harder than I'm anticipating.

**Describe alternatives you've considered**
As noted, the current workaround is `nox -- posargs`, which isn't *that* bad, it just looks a little ugly.

Other tools, designed more specifically for interactive use (like `invoke`) parse the command line more naturally, but don't have the virtual environment management features that `nox` has, so there's a lot more boilerplate needed.

**Comment by pfmoore** [comment]
Looking at the code in `nox._options` (`_posargs_finalizer`) it looks like (a) this is a deliberate restriction, but (b) it would be easy to lift. So I guess this is a design question - is the above use case sufficiently compelling to remove the restriction? Personally, I view the use case as a minor improvement in user friendliness, but I can't work out what problems the check is protecting against. So I can't really judge myself. I'll leave it up to the nox developers to take a view on this.

**Comment by theacodes** [comment]
It was an intentional design decision but I'm happy to change my mind.

The reason for doing this is part "explicit is better than implicit" and part covering us in case we add more command line args.

For example, this works as expected:

```python
$ nox -s test -- --session meep
nox > Running session test
# session.posargs = ['--session', 'meep']
nox > Session test was successful.
```

But this barfs:

```python
$ nox -s test --session meep
nox > Error while collecting sessions.
nox > Sessions not found: meep
```

So if we allowed this syntax and then later added a command-line arg that the user was using as part of their posargs, then we'd break them and in some cases, cause some unexpected behavior.

But, again, I'm happy to be talked out of this.

**Comment by cs01** [comment]
> This is not very useful. Allowing additional arguments to be handled as a posargs array (without needing --) would make for more natural command line usage in certain cases:

This only works if either all session can use the same posargs, or if there is only one session (it's probably far more common to have > 1 session in a noxfile). 

I was previously lobbying for the default handling of something like `nox serve` to run the `serve` session. What was obvious to me would have surprised you, and what is obvious to you would have surprised me. I am leaning toward the requirement for `--` since that is the least astonishing, IMO.

**Comment by tswast** [comment]
-1 from me on this request.

I've been using `nox` since the beginning, but I'm guilty of making the mistake of running something like `nox serve` and being very confused when it starts running all sessions with an additional argument. I much prefer the current explicit error than the previous behavior.

**Comment by pfmoore** [comment]
Thanks for considering this, and I appreciate the replies. The reasons behind the design decision seem fair to me. My use case is an unusual one (I was always aware of this, having a single session that does multiple things is a consequence of my working environment, and was always unlikely to be a common situation), so while the behaviour I was looking for is useful for me, it's not worth introducing ambiguities and violating the expectations of everyone else.

I'm happy to close this request on this basis, and thanks for helping me understand the motivations behind the current design better.

**Comment by theacodes** [comment]
Of course! Thanks for the thoughtful conversation. 🙂

**Comment by dhermes** [comment]
A wee example to shed some light on the why / what / how of the `--`:
```python
# double_dash.py 
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--foo")
    parser.add_argument("foo_args", nargs="+")
    args, unknown = parser.parse_known_args()
    print(args)
    print(unknown)


if __name__ == "__main__":
    main()
```

results in

```
$ python double_dash.py --foo hi --bar hey -- --baz hello
Namespace(foo='hi', foo_args=['hey', '--baz', 'hello'])
['--bar']
```

I've used this in other codebases to forward arguments from **one invocation** of my script to **many invocations** of `git grep`, so I needed my script to pass through the `git` flags without parsing them. The `--` tells the argument parser (in Python and elsewhere) to treat the arguments that follow as positional.
