### ISSUE TITLE
Current state of Windows support

### ISSUE THREAD

**Issue by brechtm** [theacodes/nox#379]
Because tox has surprised me with some very confusing behavior lately, I was looking into converting my project to use Nox instead. Initial experiments have been very pleasant. However, one paragraph in the manual makes me wonder about the state of Windows support. It mentions _"Nox has provisional support for running on Windows."_, and then links to some tox, Python and virtualenv tickets.

Since that note was added to the manual 5 years ago, I wanted to check whether Windows support is still only _provisional_. Because of the links to non-tox issues, I'm assuming that Windows support in Nox will be roughly comparable to that in tox. Could that be correct?

**Comment by stsewd** [comment]
Just linking to the docs section https://nox.thea.codes/en/stable/usage.html#windows.

So, I've seen some PRs been merged to improve the windows support since last year (or maybe more?). Personally I don't use windows, so I can't say everything works fine, but the test suite runs on Windows as well https://github.com/theacodes/nox/blob/master/appveyor.yml.

**Comment by theacodes** [comment]
Windows should work fine at this point, we can probably remove that from
the docs.

**Comment by KyleKing** [comment]
I've started using nox on Windows. My configuration has poetry and conda. I would be happy to help try to replicate any Windows-specific problems if they arise

The three related tickets linked in the documentation appear to be resolved and there hasn't been an update since ~2015. The recommended fix was to pass `shell=True` or otherwise ensure that the custom environment was properly configured for the 32-bit Python on Windows 8.1: https://bugs.python.org/issue24493#msg250848

**Comment by theacodes** [comment]
Cool, seems we should just update our docs to remove that section. :3
