### ISSUE TITLE
Add option to use pyenv instead of virtualenv?

### ISSUE THREAD

**Issue by lanshark** [theacodes/nox#4]
pyenv is an alternative way to create virtualenvs, by installing multiple copies of python (different versions).  It uses the pyenv virtualenv <version> <name> syntax instead of virtualenv <name>, and activates with pyenv activate <name>.  Should be possible as a config option.

**Comment by jonparrott** [comment]
Hmm. Can you illustrate a use case? From what I understand pyenv can help provide interpreters for virtualenv, but it does not itself handle management of virtualenvs.

**Comment by lanshark** [comment]
While pyenv does provide interpreters, it also has a plugin for creating/managing virtualenvs built from those interpreters.

https://github.com/yyuu/pyenv-virtualenv

I use that to create the virtualenvs.  Internally, pyenv uses either the venv command (if python 3) or the virtualenv command (if not). 

I have forked the project, and will try to work up a PR for you.

**Comment by jonparrott** [comment]
Cool, PRs are welcome. :+1:

**Comment by stsewd** [comment]
Why doesn't the *normal* workflow works for you? I'm using nox with pyenv like this`pyenv virtualenv 3.6 nox` and `pyenv activate nox`, actually I use a `.python-version` file to avoid having to activate pyenv manually.

**Comment by tswast** [comment]
If you are having trouble getting nox to pick the right Python when using pyenv, this guide may help: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/MAC_SETUP.md

**Comment by theacodes** [comment]
I'm thinking of closing this, unless there's something we can actually do here.

Somethings that come to mind:

1. Add explicit documentation on using pyenv to provide interpreters
2. Figure out what deeper integration we can do with pyenv.

**Comment by moshez** [comment]
I would definitely appreciate [1]. I've been fighting with getting nox to see my pyenv-ish 3.7.0 for a couple of hours.

**Comment by FollowTheProcess** [comment]
Going through some of the older issues to see if we can close any off. cc @cjolowicz 

I'm not sure this one is still relevant? Perhaps we've changed stuff in the time since this was raised but I was able to install python 3.8.12 using pyenv and run a nox session utilising this python:

(I have python 3.10.1 (pyenv), python 3.9.9 (homebrew) and this python 3.8.12 (pyenv) on my machine)

```python
# noxfile.py

import nox


@nox.session(python="3.10")
def py310(session: nox.Session) -> None:
    """
    Do stuff with 3.10
    """
    session.install("pytest")
    session.log(f"My python is {session.python}")


@nox.session(python="3.9")
def py39(session: nox.Session) -> None:
    """
    Do stuff with 3.9
    """
    session.install("pytest")
    session.log(f"My python is {session.python}")


@nox.session(python="3.8")
def py38(session: nox.Session) -> None:
    """
    Do stuff with 3.8
    """
    session.install("pytest")
    session.log(f"My python is {session.python}")

```

Which results in:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/62767721/147495308-04ea7867-b6a9-448a-bbd6-bded949954f7.png">

And catting the `.pyvenv.cfg` for `.nox/py38` reveals that the correct environment was used:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/62767721/147495550-691f42b1-96f5-4f15-9362-d0655a85fd9c.png">

The trick with pyenv is that in order for Nox to have access, you must declare the python version to be the "global" one `pyenv global 3.8.12` for example.

Or you can include a `.python-version` in the project to use it for this project only.

I tested this approach too:

```
# .python-version
3.8.12
```

<img width="589" alt="image" src="https://user-images.githubusercontent.com/62767721/147495792-9f79afbf-9ce4-4930-bbdf-cc294307e5c7.png">


<img width="601" alt="image" src="https://user-images.githubusercontent.com/62767721/147495818-c67f30f8-da28-402e-875c-d05eed320006.png">


In between each of these runs I `rm -rf`'d the whole `.nox` directory so it was the same condition each time (fresh nox run)

**Comment by cjolowicz** [comment]
Closing this as suggested by @FollowTheProcess . Happy to reopen if people want to pursue this further.

As far as I understand, there were two separate points raised in this issue:

1. Supporting pyenv-virtualenv as an additional venv backend.
2. Users experiencing problems where Nox does not use an interpreter installed with pyenv.

I'm not sure about the value of **1**, given that `pyenv-virtualenv` is a frontend to `venv` and `virtualenv` which we already support?

For users affected by **2** with a recent pyenv and virtualenv, I'd suggest to:

1. Double-check that pyenv is configured correctly and the interpreters are indeed activated (see the resource linked [above](https://github.com/theacodes/nox/issues/4#issuecomment-416349548))
2. Try removing virtualenv's cache directory if the issue persists (see https://github.com/pypa/virtualenv/issues/2130)

**Comment by neozenith** [comment]
For anyone coming to this issue later (likely me), I am totally fine with `nox` using `virtualenv` to manage the virtual environments and to discover what versions of python are on my system. The `virtualenv` <-> `pyenv` ecosystem is lacking.

However, 
 - The `pyenv globals ...` trick above wasn't working. 
 - Neither was the `pyenv-virtualenv` (because this it not what it is for) 
 - and the `virtualenv-pyenv` plugin wasn't working either, which is supposed to enhance `virtualenv` to discover `pyenv` installed versions.

Turns out `~/.pyenv/shims/` isn't enough to have on your `PATH`. Despite it showing results when I run `which -a python3.7` etc for each target version.

It seems `virtualenv` wants the `~/.pyenv/versions/X.Y.Z/bin` path on your `PATH`. 

So I created the below basic script to discover what versions are available, check if that path is not already on PATH and generate a shell command you can run yourself to update your PATH for the sake of that shell session by appending them to the end of your PATH.

```python
import os
from os import listdir
from os.path import isfile, join
from pathlib import Path

PATH = os.environ["PATH"]
# Maybe change this to get the result from subprocess.run(["pyenv", "root"])
target = Path(Path.home() / ".pyenv/versions/")

dirs = [
    d
    for d in [
        str(target / e / "bin")
        for e in os.listdir(target)
        if not isfile(join(target, e))
    ]
    if d not in PATH
]

if dirs:
    print(f"PATH=$PATH:{':'.join(dirs)}")
```

So for me it is 2 extra steps to get a `nox` testing session working with my installed `pyenv` versions:
 - Run above script
 - Update PATH

No need to reopen this ticket, just wanted to add this here since this is where google took me and I wanted to leave my solution on the bred crumb trail for the next person (most likely me again).

**Comment by everdark** [comment]
Just run into this issue today and I found that `pyenv global` works for me. 
In my case,  I have a system python `3.9.6` (`system` python) on my macOS, together with `3.9.15`, `3.10.8`, `3.8.15`, all 3 installed by `pyenv`.
`nox` can only pickup my `system` python.
For `nox` (installed in my `system` python) to find my other python versions, I simply do:

```
pyenv global system 3.9.15 3.10.8 3.8.15
```

and it now works as expected.
for py39 `nox` will use my system, but if I change the order of the `pyenv global` it will also use the one from `pyenv`.

Hope this helps for whoever run into this in the future. :)
