### ISSUE TITLE
Session.posargs should be immutable

### ISSUE THREAD

**Issue by rmorshea** [theacodes/nox#400]
There's no reason that `Session.posargs` should be mutated by users.

> ...a tuple would be preferable ...[and] might not even constitute a breaking change

_Originally posted by @cjolowicz in https://github.com/theacodes/nox/pull/397#discussion_r591857948_

**Comment by cjolowicz** [comment]
Thanks for creating the issue @rmorshea !

Here's an example to illustrate the problem:

```python
import nox

@nox.session
def test(session):
    session.posargs.extend(["-x"])
    session.install("pytest")
    session.run("pytest", *session.posargs)

@nox.session
def lint(session):
    args = [*session.posargs, "src"]
    session.install("flake8")
    session.run("flake8", *args)
```

The lint session will fail with `flake8: error: unrecognized arguments: -x`.

**Comment by cjolowicz** [comment]
In the context of #397, we discussed two approaches to solve this:

- Returning a copy using something like `global_config.posargs[:]`
- Returning a tuple instead of a list

On further thought, I'm worried that option 2 would break users that expect `session.posargs` to be a list:

```python
@nox.session
def test(session):
    args = session.posargs + ["--full-trace", "--verbose"]
```

It's true that typically `session.posargs` is unpacked into `session.run`, and the precise type of `session.posargs` is not documented. But by [Hyrum's Law](https://www.hyrumslaw.com/) some people will depend on it being a list nonetheless.

Option 1 will require some updates to the test suite, but should not break existing Noxfiles. See https://github.com/theacodes/nox/pull/397#discussion_r590169556 for a patch that updates the tests accordingly.

**Comment by rmorshea** [comment]
@cjolowicz good point about the list additions. I think I do that myself actually. Copying the list might be the right approach here. I feel like there's a lot more people who will be harmed by changing this to a tuple than would be protected by its immutability?

**Comment by vaneseltine** [comment]
Yes, flipping through [a few examples](https://github.com/search?l=&q=session.posargs+filename%3Anoxfile&type=Code) most of them use generic sequence methods like `in` and unpacking, but it didn't take long to come across list concatenation in the wild

And I think I might have found a superspreader for one common pattern...

[pip](https://github.com/pypa/pip/blob/main/noxfile.py):

```python
@nox.session
def lint(session):
    # type: (nox.Session) -> None
    session.install("pre-commit")

    if session.posargs:
        args = session.posargs + ["--all-files"]
    else:
        args = ["--all-files", "--show-diff-on-failure"]

    session.run("pre-commit", "run", *args)
```

So while a tuple might have been best from the outset, given what's in the wild, copying the list seems like a reasonable approach.
