### ISSUE TITLE
Cannot run nox twice with conda on Windows

### ISSUE THREAD

**Issue by bcassell** [theacodes/nox#468]
**Describe the bug**

On Windows, trying to use conda with nox, the first run is fine, but the second run gives:

`
Session unit_tests raised exception PermissionError(13, 'Access is denied')
...
PermissionError: [WinError 5] Access is denied: '<Redacted>\.nox\\unit_tests\\Library\\bin\\libcrypto-1_1-x64.dll.c~.conda_trash.conda_trash'
`

**How to reproduce**

noxfile.py looks like:
```
import nox

@nox.session(venv_backend="conda")
def unit_tests(session: Session):
    session.conda_install('pytest')
    session.run(
        "pytest",
        "-m",
        "unit",
        "tests"
    )
```

$> nox

Using latest conda.

For what its worth, it seems like this issue doesn't manifest if nox is installed in the system python (as opposed to conda base).

**Expected behavior**
Subsequent runs do not fail due to permission errors.

**Comment by FollowTheProcess** [comment]
Hi @bcassell !

I suspect this is a windows issue and not necessarily a `nox` issue.

The `PermissionError` is a common occurrence in python on windows due to the nitpicky details of how windows handles programs that spawn other programs `subprocesses`, which nox does a lot of!

It's to do with which (if any) of your subprocess has access to various folders and files. My suspicion is that the system python doesn't cause a problem because it's more than likely running under higher privileges compared to a python process started in a conda environment.

If you're not on python >=3.7.3 you should upgrade as this is a well known problem in earlier versions: [https://bugs.python.org/issue35797](https://bugs.python.org/issue35797).

I would start by ensuring you have admin permissions on all the folders and files in your project, (I haven't used windows for a while so I can't exactly remember how to do this but I imagine something along the lines of right clicking and looking for 'properties' or similar)

Have you tried running nox from a command prompt (or powershell) started as admin i.e. right click and choose "run as administrator" then cd to your project and try running nox again.

Does this problem still occur if you create a virtual environment using python (not conda) and use the default nox backend and `session.install`? If so it could be a conda related issue.

Without knowing more it's difficult to give suggestions but hope this helped.

**Comment by bcassell** [comment]
This was using python 3.8.10. I've gone with a different solution (based on invoke) because complete conda support is not quite there with nox (though I appreciate the effort and expect that things would work better on Linux!), and if I need to more explicitly manage my envs/build processes, and especially chain tasks togther, it seems like invoke is better suited for that.

**Comment by FollowTheProcess** [comment]
Cool! Whatever tool makes you the most productive, thanks for filing the bug!

**Comment by cjolowicz** [comment]
Can this be closed?
