### ISSUE TITLE
Working directory unexpectedly set to wherever noxfile.py is.

### ISSUE THREAD

**Issue by bcassell** [theacodes/nox#469]
**Describe the bug**
Trying to invoke nox from a different folder using the --noxfile flag sets the current working directory to where the noxfile lives.  This makes reusing a noxfile across multiple projects in a monorepo very difficult, since I can't find a good way to set the current working directory to where nox was called from.  Even passing '.' as a posarg will end up being interpreted as the directory where the noxfile lives

**Expected behavior**
Either the cwd stays as wherever nox is called from, or we have some command line arg for what to treat as the cwd.  If this feature already exists and I've missed it, or there are some other recommendations for how to use a single nox file across multiple projects, please let me know!

**Comment by theacodes** [comment]
This is very much intentional behavior and it's too let noxfiles care less about how it was executed - specifically, so it can make assumptions about where it's working from.

I think we could make the original cwd available as a property of the session, though. The chdir happens [here](https://github.com/theacodes/nox/blob/8ee3ebed052ed7eeef0151a424929039dd479b94/nox/tasks.py#L64).

**Comment by bcassell** [comment]
Available as a session property would be perfect.

**Comment by DiddiLeija** [comment]
Hello @theacodes. I'm interested on this issue, if no one is working on it. Can you please tell me what do I have to do (I'm a bit new to the concept)?

**Comment by theacodes** [comment]
@DiddiLeija you could store the original cwd in `global_config` and then allow the session to access that. The code starts here: https://github.com/theacodes/nox/blob/8ee3ebed052ed7eeef0151a424929039dd479b94/nox/tasks.py#L64

**Comment by DiddiLeija** [comment]
Got it. I will open a PR on the next week.
