### ISSUE TITLE
Document how runs cause sessions to fail

### ISSUE THREAD

**Issue by ktbarrett** [theacodes/nox#517]
**How would this feature be useful?**

I need to always run cleanup code when a task fails. I didn't know how to accomplish that until I realized that sessions fail when `session.run`s raise `CommandFailed`. The use of exceptions here means I can cleanup by using a finally block. For example,

```python
@nox.session(reuse_venv=True)
def check(session):
    build_env(session)
    try:
        session.run("git", "stash", "-k", "-u")
        session.run("isort", "--check-only", "--profile=black", ".")
        session.run("black", "--check", ".")
        session.run("mypy", "--strict", ".")
    finally:
        session.run("git", "stash", "pop")
```

**Describe the solution you'd like**

Taking the outcome of #516 into account, documenting that this is possible may help other users learn understand what is possible.

**Comment by cjolowicz** [comment]
Thanks for catching this! Indeed, the documentation is not explicit about what happens when a command run via `session.run` fails. This could be a sentence added to the docstring of `nox.sessions.Session.run`.

I also agree that mentioning the pattern of wrapping a `try...finally` around `session.run` for cleanup actions is worth mentioning. Not sure about mentioning `CommandFailed` specifically, as it's currently not part of the public API.

**Comment by ktbarrett** [comment]
Also, maybe I missed it, but I never saw it mentioned anywhere that `session.run` fails the current session immediately. 

> `session.run` causes the current session to fail immediately
> all sessions listed are always run and if any sessions fail the `nox` invocation fails
