### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#9]

**Comment by theacodes** [comment]
I don't think I'm going to do this right now. I'm happy to revisit if others feel it might be useful.

**Comment by theacodes** [comment]
@TheKevJames awesome! If you would like, it'd be cool to add that to the documentation as an alternative way to install nox. What do you think?

**Comment by TheKevJames** [comment]
@theacodes absolutely, that sounds good to me!

**Comment by funkyfuture** [comment]
i'm in a situation (compilation of CPython3.7 fails weirdly on Ubuntu 20.10) where my approach would rather be to extend nox so that Docker/Moby (and perspectively other container solutions) can be used as `venv_backend`. i haven't looked into the codebase to estimate the effort yet, so my question is whether that is something you'd be generally interested in.
