### ISSUE TITLE
Make nox imperative, not declarative. 

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#91]
Because Nox collects all commands before executing them it's hard to do any sort of branching logic in sessions. We should consider changing Nox to be imperative. I argue that this is closer to how people actually conceptualize the session.

There is *one* big problem with this approach right now: the virtualenv configuration. Presently, you can tell Nox how to make your virtualenv by setting properties on the session:

```python
@nox.session
def tests(s):
    s.interpreter = 'python3.6'
```

Unfortunately we can't do this if we switch to imperative. There are two options I can think of:

*Option 1*: Remove all of the properties and add a new imperative command called `virtualenv` to the session. It will create the virtualenv and then all following commands will use the virtualenv configuration:

```python
@nox.session
def tests(s):
    s.virtualenv('python3.6')
    s.run('python' ,'--version')   # uses Python in the virtualenv.
```

This unfortunately will break almost every nox script currently in existence, but the "fix" is relatively straightforward and I could maybe even write a tool that will migrate for you. Also, the change in behavior from declarative to imperative might break some people.

*Option 2*: Do some magic. Almost all nox scripts in existence setup the virtualenv properties before calling `install` or `run`. We could make nox create the virtualenv on the first call to either `install` or `run`. I'm not a huge fan of this, but it would be mostly backwards-compatible. 

/cc @pradyunsg @lukesneeringer @dhermes

**Comment by theacodes** [comment]
Related #90 #73

**Comment by dhermes** [comment]
> This unfortunately will break almost every nox script currently in existence

I think that's probably fine. Do you have any sense for who is using it other than "us"? (i.e. `google-cloud-python` and related folks)

**Comment by theacodes** [comment]
packaging.python.org and the Google assistant SDK as well. Maybe a few
others. I need to research a bit more.

**Comment by pradyunsg** [comment]
> Make it an @property?

That's option 2. I feel a little stupid for suggesting this now. :P

**Comment by lukesneeringer** [comment]
I have an alternate suggestion (option 3) that _might_ be backwards compatible, but has the disadvantage of being, well, kind of hard and leaves legacy code in place.

Essentially, make the Python version a first-class argument to `@nox.session`, and use imperative mode if and only if it is in place. Usage would look like:

```python
@nox.session(python='3.7')
@nox.session(python=['2.7', '3.4', '3.5', '3.6', 3.7'])
```

This solution has some pros and cons:

PRO 1. One of the single more annoying things about nox is how awkward it is to do something like `nox -s "unit(py='3.7')"`, which is excessively pedantic (for example: if you swap the single and double quotes, it fails). Similarly, a really common use case can be to want to run _all_ sessions on _one_ Python version, which is very verbose right now. This approach would allow for a `--python` switch which would handle this situation gracefully:

```
$ nox -s unit -p 3.7
$ nox -p 3.7
```

PRO 2. It can be done in a backwardsly-compatible way with current nox scripts.

CON 1. It is not compatible with the `def session_foo` idiom for declaring sessions. I do not really think that idiom is used often, since people often do care about ordering. But anyone who wants to use that is stuck in declarative mode; this would _only_ work with the decorator.

CON 2. Bloat in nox itself; the code for both modes would have to be maintained.

**Comment by lukesneeringer** [comment]
PRO 3. It would make solving #93 very very easy. :-)

**Comment by theacodes** [comment]
I'm really going to try to find some time to do this overhaul soon. I have
a bunch of travel coming up, so that might be tricky but it's definitely
popping up a bit more.

**Comment by theacodes** [comment]
Started work on this today, you can follow progress over at https://github.com/theacodes/nox/pull/94

**Comment by theacodes** [comment]
#94 has been merged. I have a bit more cleanup work to do before I can release it, but I'm gonna go ahead and close this. Feel free to test against head and let me know how it works for you!
